In [5]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [7]:
df = pd.read_csv('Cleaned_dataset.csv')

In [8]:
df.sample(4)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
86,1477348,23,0.075,0.069142,0,0.035714,0.000,0.298093,0.666667,0,0.0,0.000000,0,0,0.666667,0.333333,0.666667,0.142857,2,0
815,1308397,31,0.075,0.093839,0,0.678571,0.050,0.798514,1.000000,0,0.0,0.111111,2,2,0.666667,0.333333,0.666667,0.071429,1,0
22,1705718,34,0.325,0.578462,0,0.214286,0.300,0.770889,0.666667,0,0.5,0.333333,2,11,0.000000,0.000000,0.666667,0.000000,0,0
256,1068917,42,0.250,0.083412,1,0.035714,0.225,0.237422,0.333333,1,0.0,0.333333,7,8,1.000000,0.333333,0.666667,0.000000,2,0

In [14]:
rows, columns = df.shape
print(f'Rows    : {rows}')
print(f'Columns : {columns}')
df.describe()

Rows    : 1676
Columns : 20

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
count,1.676000e+03,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000
mean,1.456796e+06,36.866348,0.283473,0.290022,0.284010,0.293641,0.175835,0.489581,0.574980,0.960024,0.266706,0.236940,2.200477,4.135442,0.571599,0.268695,0.588703,0.299778,0.913484,0.118735
std,2.487486e+05,9.129126,0.195875,0.248997,0.451076,0.291361,0.152475,0.286644,0.238040,0.889179,0.278356,0.201525,3.229587,3.559662,0.365845,0.285176,0.234123,0.260468,0.727480,0.323573
min,1.025177e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.235832e+06,30.000000,0.150000,0.101066,0.000000,0.035714,0.075000,0.236860,0.333333,0.000000,0.000000,0.111111,0.000000,2.000000,0.333333,0.000000,0.333333,0.071429,0.000000,0.000000
50%,1.464606e+06,36.000000,0.250000,0.204845,0.000000,0.214286,0.125000,0.488878,0.666667,1.000000,0.250000,0.166667,1.000000,3.000000,0.666667,0.333333,0.666667,0.214286,1.000000,0.000000
75%,1.667992e+06,43.000000,0.375000,0.388165,1.000000,0.464286,0.250000,0.737523,0.666667,1.000000,0.500000,0.388889,3.000000,7.000000,1.000000,0.333333,0.666667,0.500000,1.000000,0.000000
max,1.886378e+06,60.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,15.000000,17.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000

In [25]:
y = df['Attrition'] # test data
X = df.drop(['Attrition'], axis=1) #training data

print(f'Training data: {X.columns}\n')
print(f'Testing data : {y.name}')

Training data: Index(['EmployeeID', 'Age', 'TotalWorkingYears', 'MonthlyIncome', 'OverTime',
       'DistanceFromHome', 'YearsAtCompany', 'MonthlyRate', 'JobInvolvement',
       'JobRole', 'JobLevel', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'EnvironmentSatisfaction', 'Shift',
       'WorkLifeBalance', 'PercentSalaryHike', 'MaritalStatus'],
      dtype='object')

Testing data : Attrition

In [57]:
y.unique()

array([0, 1])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [29]:
print(f'X_train : {X_train.shape}')
print(f'X_test  : {X_test.shape}\n')
print(f'y_train : {y_train.shape}')
print(f'y_test  : {y_test.shape}')

X_train : (1340, 19)
X_test  : (336, 19)

y_train : (1340,)
y_test  : (336,)

In [75]:
# Number of trees in random forest
random_values = np.linspace(50, 101, 10) 
# values = []
# for i in random_values: 
#     values.append(int(i))
# n_estimators = [values]
n_estimators = [int(i) for i in random_values]

# Number of features to consider at every split
max_features = ['log2', 'sqrt']

# Maximum number of levels in tree
max_depth = [5, 10]

# Minimum number of samples required to split a node
min_samples_split = [2, 5]

# Minimum number of samples reqiured at each leaf node
min_sample_leaf = [10, 20]

# Method of selecting samples for training each tree
bootsstrap = [True, False]

In [76]:
param_grid = {
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_sample_leaf,
    'bootstrap': bootsstrap
}
print(param_grid)

{'n_estimators': [50, 55, 61, 67, 72, 78, 84, 89, 95, 101], 'max_features': ['log2', 'sqrt'], 'max_depth': [5, 10], 'min_samples_split': [2, 5], 'min_samples_leaf': [10, 20], 'bootstrap': [True, False]}

In [77]:
rfc = RandomForestClassifier(101)

In [78]:
from sklearn.model_selection import GridSearchCV
rfc_grid = GridSearchCV(rfc, param_grid, cv=3, verbose=2, n_jobs=4, error_score='raise') # estimator, param_grid, cv, verbose, n_jobs
# 'verbose' gives information about the process while the fitting is happening
#  'n_jobs' use the number of cores in the cpu for this process

In [79]:
rfc_grid.fit(X_train, y_train)

Fitting 3 folds for each of 320 candidates, totalling 960 fits

AttributeError: 'bool' object has no attribute 'all'

AttributeError: 'bool' object has no attribute 'all'

GridSearchCV(cv=3, error_score='raise',
             estimator=RandomForestClassifier(n_estimators=101), n_jobs=4,
             param_grid={'bootstrap': [True, False], 'max_depth': [5, 10],
                         'max_features': ['log2', 'sqrt'],
                         'min_samples_leaf': [10, 20],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 55, 61, 67, 72, 78, 84, 89, 95,
                                          101]},
             verbose=2)

In [81]:
rfc_grid.best_params_

{'bootstrap': False,
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 10,
 'min_samples_split': 2,
 'n_estimators': 95}

In [85]:
print(f'Train Accuracy: {rfc_grid.score(X_train, y_train):.3f}')
print(f'Test Accuracy: {rfc_grid.score(X_train, y_train):.3f}')

Train Accuracy: 0.933
Test Accuracy: 0.933