In [23]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('Cleaned_dataset.csv')

In [3]:
df.sample(4)

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
738,1212094,42,0.525,0.910690,0,0.142857,0.025,0.227906,0.666667,3,1.00,0.000000,0,0,1.000000,0.000000,1.000000,0.142857,1,0
607,1282527,43,0.550,0.850448,0,0.464286,0.100,0.124714,0.666667,3,0.75,0.055556,1,0,0.333333,0.333333,0.666667,0.928571,1,0
1429,1818407,25,0.150,0.205266,1,0.250000,0.125,0.465368,0.666667,1,0.25,0.166667,0,4,0.000000,0.333333,0.333333,0.785714,2,0
1194,1119867,20,0.050,0.090521,0,0.285714,0.050,0.762417,0.666667,0,0.00,0.111111,0,2,1.000000,0.000000,0.666667,0.000000,0,0

In [4]:
rows, columns = df.shape
print(f'Rows    : {rows}')
print(f'Columns : {columns}')
df.describe()

Rows    : 1676
Columns : 20

,EmployeeID,Age,TotalWorkingYears,MonthlyIncome,OverTime,DistanceFromHome,YearsAtCompany,MonthlyRate,JobInvolvement,JobRole,JobLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,Shift,WorkLifeBalance,PercentSalaryHike,MaritalStatus,Attrition
count,1.676000e+03,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000,1676.000000
mean,1.456796e+06,36.866348,0.283473,0.290022,0.284010,0.293641,0.175835,0.489581,0.574980,0.960024,0.266706,0.236940,2.200477,4.135442,0.571599,0.268695,0.588703,0.299778,0.913484,0.118735
std,2.487486e+05,9.129126,0.195875,0.248997,0.451076,0.291361,0.152475,0.286644,0.238040,0.889179,0.278356,0.201525,3.229587,3.559662,0.365845,0.285176,0.234123,0.260468,0.727480,0.323573
min,1.025177e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.235832e+06,30.000000,0.150000,0.101066,0.000000,0.035714,0.075000,0.236860,0.333333,0.000000,0.000000,0.111111,0.000000,2.000000,0.333333,0.000000,0.333333,0.071429,0.000000,0.000000
50%,1.464606e+06,36.000000,0.250000,0.204845,0.000000,0.214286,0.125000,0.488878,0.666667,1.000000,0.250000,0.166667,1.000000,3.000000,0.666667,0.333333,0.666667,0.214286,1.000000,0.000000
75%,1.667992e+06,43.000000,0.375000,0.388165,1.000000,0.464286,0.250000,0.737523,0.666667,1.000000,0.500000,0.388889,3.000000,7.000000,1.000000,0.333333,0.666667,0.500000,1.000000,0.000000
max,1.886378e+06,60.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000,15.000000,17.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000

In [5]:
y = df['Attrition'] # test data
X = df.drop(['Attrition'], axis=1) #training data

print(f'Training data: {X.columns}\n')
print(f'Testing data : {y.name}')

Training data: Index(['EmployeeID', 'Age', 'TotalWorkingYears', 'MonthlyIncome', 'OverTime',
       'DistanceFromHome', 'YearsAtCompany', 'MonthlyRate', 'JobInvolvement',
       'JobRole', 'JobLevel', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'EnvironmentSatisfaction', 'Shift',
       'WorkLifeBalance', 'PercentSalaryHike', 'MaritalStatus'],
      dtype='object')

Testing data : Attrition

In [6]:
y.unique()

array([0, 1])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [8]:
print(f'X_train : {X_train.shape}')
print(f'X_test  : {X_test.shape}\n')
print(f'y_train : {y_train.shape}')
print(f'y_test  : {y_test.shape}')

X_train : (1340, 19)
X_test  : (336, 19)

y_train : (1340,)
y_test  : (336,)

In [21]:
# Before RandomForestClassifier

rfc_model = RandomForestClassifier(n_estimators=100, random_state=101)
rfc_model.fit(X_train, y_train)

RandomForestClassifier(random_state=101)

In [28]:
train_score_before_hpt = rfc_model.score(X_train, y_train)
test_score_brefore_hpt = rfc_model.score(X_test, y_test)

In [29]:
print(f'Train score: {train_score_before_hpt:.3f}')
print(f'Test score : {test_score_brefore_hpt:.3f}')

Train score: 1.0
Test score : 0.9196428571428571

In [11]:
# Number of trees in random forest
random_values = np.linspace(50, 101, 10) 
# values = []
# for i in random_values: 
#     values.append(int(i))
# n_estimators = [values]
n_estimators = [int(i) for i in random_values]

# Number of features to consider at every split
max_features = ['log2', 'sqrt']

# Maximum number of levels in tree
max_depth = [5, 10]

# Minimum number of samples required to split a node
min_samples_split = [2, 5]

# Minimum number of samples reqiured at each leaf node
min_sample_leaf = [10, 20]

# Method of selecting samples for training each tree
bootsstrap = [True, False]

In [12]:
param_grid = {
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_sample_leaf,
    'bootstrap': bootsstrap
}
print(param_grid)

{'n_estimators': [50, 55, 61, 67, 72, 78, 84, 89, 95, 101], 'max_features': ['log2', 'sqrt'], 'max_depth': [5, 10], 'min_samples_split': [2, 5], 'min_samples_leaf': [10, 20], 'bootstrap': [True, False]}

In [13]:
rfc = RandomForestClassifier(101)

In [14]:
from sklearn.model_selection import GridSearchCV
rfc_grid = GridSearchCV(rfc, param_grid, cv=3, verbose=2, n_jobs=4, error_score='raise') # estimator, param_grid, cv, verbose, n_jobs
# 'verbose' gives information about the process while the fitting is happening
#  'n_jobs' use the number of cores in the cpu for this process

In [15]:
rfc_grid.fit(X_train, y_train)

Fitting 3 folds for each of 320 candidates, totalling 960 fits

AttributeError: 'bool' object has no attribute 'all'

AttributeError: 'bool' object has no attribute 'all'

GridSearchCV(cv=3, error_score='raise',
             estimator=RandomForestClassifier(n_estimators=101), n_jobs=4,
             param_grid={'bootstrap': [True, False], 'max_depth': [5, 10],
                         'max_features': ['log2', 'sqrt'],
                         'min_samples_leaf': [10, 20],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 55, 61, 67, 72, 78, 84, 89, 95,
                                          101]},
             verbose=2)

In [16]:
rfc_grid.best_params_

{'bootstrap': False,
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 10,
 'min_samples_split': 2,
 'n_estimators': 89}

In [30]:
train_score_after_hpt = rfc_grid.score(X_train, y_train)
test_score_after_hpt = rfc_grid.score(X_test, y_test)

In [42]:
print(f'Train Accuracy Before Hyperparameter Tuning: {train_score_before_hpt:.3f}        # Overfitting is clealy visible')
print(f'Test Accuracy Before Hyperparameter Tuning : {test_score_brefore_hpt:.3f}\n')

print(f'Train Accuracy After Hyperparameter Tuning: {train_score_after_hpt:.3f}         # Minimized overfitting')
print(f'Test Accuracy After Hyperparameter Tuning : {test_score_after_hpt:.3f}')

Train Accuracy Before Hyperparameter Tuning: 1.000        # Overfitting is clealy visible
Test Accuracy Before Hyperparameter Tuning : 0.920

Train Accuracy After Hyperparameter Tuning: 0.934         # Minimized overfitting
Test Accuracy After Hyperparameter Tuning : 0.899

In [45]:
difference_before = train_score_before_hpt - test_score_brefore_hpt
difference_after = train_score_after_hpt - test_score_after_hpt
print(f'Difference between train and test cases before HPT: {difference_before:.4f}')
print(f'Difference between train and test cases after HPT: {difference_after:.4f}\n')

print(f'Accuracy improvement : {difference_before - difference_after:.4f}')

Difference between train and test cases before HPT: 0.0804
Difference between train and test cases after HPT: 0.0348

Accuracy improvement : 0.0456

The conclusion is Hyperparameter tunining reduces over fitting and increases the accuracy by 0.0456