## Data Preprocessing

In [13]:
import pandas as pd

In [14]:
dataframe = pd.read_csv('watson_healthcare_modified.csv')
dataframe.sample(4)

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
965,1408258,36,No,Travel_Frequently,607,Cardiology,7,3,Marketing,1,...,4,80,1,17,2,2,15,7,6,13
745,1665250,26,Yes,Non-Travel,265,Cardiology,29,2,Medical,1,...,4,80,0,7,6,3,2,2,2,2
455,1670281,31,No,Travel_Rarely,688,Cardiology,7,3,Life Sciences,1,...,3,80,1,10,3,2,5,4,0,1
393,1550660,34,No,Non-Travel,1381,Cardiology,4,4,Marketing,1,...,1,80,1,6,3,3,3,2,1,2

In [15]:
dataframe.shape

(1676, 35)

In [16]:
dataframe.select_dtypes(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,No,Travel_Rarely,Cardiology,Life Sciences,Female,Nurse,Single,Y,Yes
1,No,Travel_Frequently,Maternity,Life Sciences,Male,Other,Married,Y,No
2,Yes,Travel_Rarely,Maternity,Other,Male,Nurse,Single,Y,Yes
3,No,Travel_Frequently,Maternity,Life Sciences,Female,Other,Married,Y,Yes
4,No,Travel_Rarely,Maternity,Medical,Male,Nurse,Married,Y,No
...,...,...,...,...,...,...,...,...,...
1671,Yes,Travel_Rarely,Neurology,Technical Degree,Male,Nurse,Single,Y,Yes
1672,No,Travel_Rarely,Cardiology,Marketing,Female,Nurse,Married,Y,Yes
1673,No,Travel_Rarely,Maternity,Life Sciences,Female,Other,Single,Y,No
1674,No,Travel_Rarely,Neurology,Life Sciences,Female,Therapist,Married,Y,No
1675,No,Travel_Rarely,Cardiology,Medical,Female,Nurse,Single,Y,No

In [17]:
dframe = dataframe.copy()
dframe.tail(5)
del dataframe # For original dataset safety

### Train/Test Splitting

In [18]:
y = dframe['Attrition']
X = dframe.drop('Attrition', axis=1)

In [19]:
(dframe.dtypes).unique()
del dframe # Save memory

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [22]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape)

(1340, 34)

(336, 34)

(1340,)

(336,)

Encoding only the train sets to prevent data leakage

#### Attrition Mapping

In [23]:
# mapping attrition columns to 1s and 0s
y_test = y_test.map({'Yes': 1, 'No': 0})
y_train = y_train.map({'Yes': 1, 'No': 0})
display(y_test.head(7))
display(y_train.tail(7))

1260    0
709     1
261     0
107     1
1639    0
228     0
1226    0
Name: Attrition, dtype: int64

382     0
428     0
735     0
1350    1
71      0
320     0
552     0
Name: Attrition, dtype: int64

#### Test set unwanted feature deletion

In [24]:
dropping_columns = ['EmployeeID', 'Over18', 'EmployeeCount', 'StandardHours']
X_test.drop(dropping_columns, axis=1, inplace=True)
X_test.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1260,42,Travel_Rarely,855,Maternity,12,3,Medical,2,Male,57,...,4,2,3,7,6,2,5,3,0,4
709,29,Travel_Rarely,906,Maternity,10,3,Life Sciences,4,Female,92,...,4,3,0,3,5,3,0,0,0,0
261,38,Non-Travel,1327,Cardiology,2,2,Life Sciences,4,Male,39,...,3,4,1,13,0,3,8,7,7,5
107,25,Travel_Rarely,240,Cardiology,5,3,Marketing,3,Male,46,...,3,4,0,6,1,3,6,4,0,3
1639,29,Travel_Rarely,352,Neurology,6,1,Medical,4,Male,87,...,3,4,0,1,3,3,1,0,0,0

#### Train set unwanted feature deletion

In [26]:
X_train.drop(dropping_columns, axis=1, inplace=True)
X_train.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,Travel_Rarely,1398,Cardiology,2,4,Life Sciences,3,Female,79,...,3,4,0,21,2,3,20,15,1,12
243,40,Travel_Rarely,1300,Maternity,24,2,Technical Degree,1,Male,62,...,3,1,2,9,3,3,9,8,4,7
1628,25,Travel_Rarely,622,Cardiology,13,1,Medical,2,Male,40,...,3,3,0,7,1,3,7,4,0,6
454,33,Travel_Rarely,922,Maternity,1,5,Medical,1,Female,95,...,3,3,1,10,2,3,6,1,0,5
1532,39,Travel_Frequently,505,Maternity,2,4,Technical Degree,3,Female,64,...,4,4,0,20,1,3,19,6,11,8

In [28]:
X_train.select_dtypes(include='int64')

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
417,40,1398,2,4,3,79,3,5,3,18041,...,3,4,0,21,2,3,20,15,1,12
243,40,1300,24,2,1,62,3,2,4,3319,...,3,1,2,9,3,3,9,8,4,7
1628,25,622,13,1,2,40,3,1,3,2096,...,3,3,0,7,1,3,7,4,0,6
454,33,922,1,5,1,95,4,4,3,16184,...,3,3,1,10,2,3,6,1,0,5
1532,39,505,2,4,3,64,3,3,3,10938,...,4,4,0,20,1,3,19,6,11,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,41,549,7,2,4,42,3,2,3,5003,...,3,2,0,8,6,3,2,2,2,1
1350,56,1162,24,2,1,97,3,1,4,2587,...,3,4,0,5,3,3,4,2,1,0
71,29,1328,2,3,3,76,3,1,2,2703,...,4,4,1,6,3,3,5,4,0,4
320,27,1377,2,3,4,74,3,2,3,4478,...,3,1,0,5,3,3,5,4,0,4
552,27,975,7,3,4,55,2,2,1,6811,...,3,1,0,9,2,1,7,6,0,7

In [29]:
X_train.select_dtypes(include='object')

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
417,Travel_Rarely,Cardiology,Life Sciences,Female,Administrative,Married,No
243,Travel_Rarely,Maternity,Technical Degree,Male,Other,Divorced,No
1628,Travel_Rarely,Cardiology,Medical,Male,Other,Married,No
454,Travel_Rarely,Maternity,Medical,Female,Administrative,Divorced,No
1532,Travel_Frequently,Maternity,Technical Degree,Female,Other,Single,No
...,...,...,...,...,...,...,...
735,Travel_Rarely,Cardiology,Medical,Female,Therapist,Single,No
1350,Travel_Rarely,Neurology,Life Sciences,Male,Nurse,Single,No
71,Travel_Rarely,Maternity,Life Sciences,Male,Other,Married,No
320,Travel_Rarely,Cardiology,Life Sciences,Male,Nurse,Single,Yes
552,Travel_Rarely,Maternity,Medical,Female,Nurse,Single,No

### Encoding Objects to Numerical Values

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='error').set_output(transform='pandas')

#### Gender and Department encoding (ohe) and merging

In [33]:
enc_gender = ohe.fit_transform(X_train[['Gender']])
trans_gender = ohe.transform(X_test[['Gender']])
enc_department = ohe.fit_transform(X_train[['Department']])
trans_department = ohe.transform(X_test[['Department']])

In [34]:
display(enc_gender.sample(5))
display(trans_gender.sample(5))

      Gender_Female  Gender_Male
1624            0.0          1.0
438             0.0          1.0
1267            1.0          0.0
1455            0.0          1.0
320             0.0          1.0

      Gender_Female  Gender_Male
737             0.0          1.0
653             0.0          1.0
911             0.0          1.0
100             0.0          1.0
1161            1.0          0.0

In [35]:
display(enc_department.sample(4))
display(trans_department.sample(4))

      Department_Cardiology  Department_Maternity  Department_Neurology
386                     0.0                   1.0                   0.0
1184                    0.0                   1.0                   0.0
1538                    0.0                   0.0                   1.0
1310                    0.0                   0.0                   1.0

      Department_Cardiology  Department_Maternity  Department_Neurology
141                     0.0                   1.0                   0.0
230                     0.0                   1.0                   0.0
515                     1.0                   0.0                   0.0
1457                    1.0                   0.0                   0.0

In [36]:
X_train = pd.concat([X_train, enc_department], axis=1).drop(columns=['Department'])
X_test = pd.concat([X_test, trans_department], axis=1).drop(columns=['Department'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
862,30,Travel_Rarely,1329,29,4,Life Sciences,3,Male,61,3,...,8,3,3,4,3,0,3,1.0,0.0,0.0
29,46,Travel_Rarely,705,2,4,Marketing,2,Female,83,3,...,22,2,2,2,2,2,1,1.0,0.0,0.0
1468,45,Travel_Rarely,1329,2,2,Other,4,Female,59,2,...,10,3,3,10,7,3,9,0.0,1.0,0.0
1510,31,Travel_Rarely,655,7,4,Life Sciences,4,Male,48,3,...,10,3,2,7,7,1,7,0.0,0.0,1.0
1065,28,Travel_Frequently,289,2,2,Medical,3,Male,38,2,...,8,2,2,0,0,0,0,0.0,1.0,0.0

Train Set: (1340, 32)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology
105,59,Non-Travel,1420,2,4,Human Resources,3,Female,32,2,...,30,3,3,3,2,2,2,0.0,0.0,1.0
496,22,Travel_Rarely,604,6,1,Medical,1,Male,69,3,...,3,3,3,2,2,2,2,0.0,1.0,0.0
1659,26,Non-Travel,265,29,2,Medical,2,Male,79,1,...,7,6,3,2,2,2,2,1.0,0.0,0.0
1300,47,Travel_Rarely,1001,4,3,Life Sciences,3,Female,92,2,...,28,4,3,22,11,14,10,1.0,0.0,0.0
1159,35,Travel_Rarely,737,10,3,Medical,4,Male,55,2,...,15,3,3,13,12,6,0,1.0,0.0,0.0

In [37]:
X_train = pd.concat([X_train, enc_gender], axis=1).drop(columns=['Gender'])
X_test = pd.concat([X_test, trans_gender], axis=1).drop(columns=['Gender'])
print(f'Test Set: {X_test.shape}')
display(X_test.sample(5))
print(f'Train Set: {X_train.shape}')
display(X_train.sample(5))

Test Set: (336, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
888,44,Travel_Rarely,1117,2,1,Life Sciences,1,72,4,1,...,3,10,5,7,7,0.0,1.0,0.0,1.0,0.0
333,43,Travel_Rarely,1001,7,3,Life Sciences,3,43,3,3,...,2,1,0,0,0,0.0,1.0,0.0,1.0,0.0
1232,46,Travel_Rarely,1277,2,3,Life Sciences,3,74,3,3,...,2,10,6,0,3,1.0,0.0,0.0,0.0,1.0
497,33,Travel_Rarely,1216,8,4,Marketing,3,39,3,2,...,3,5,0,1,2,1.0,0.0,0.0,0.0,1.0
978,35,Travel_Frequently,662,18,4,Marketing,4,67,3,2,...,2,4,2,3,2,1.0,0.0,0.0,1.0,0.0

Train Set: (1340, 33)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1354,31,Travel_Rarely,1079,10,2,Medical,3,86,3,2,...,3,5,2,1,4,1.0,0.0,0.0,1.0,0.0
559,52,Travel_Rarely,621,3,4,Marketing,3,31,2,4,...,4,34,6,1,16,1.0,0.0,0.0,0.0,1.0
1458,39,Travel_Rarely,722,24,1,Marketing,2,60,2,4,...,2,20,9,9,6,1.0,0.0,0.0,1.0,0.0
1622,27,Non-Travel,691,9,3,Medical,4,57,3,1,...,1,2,2,2,2,0.0,1.0,0.0,0.0,1.0
558,34,Travel_Rarely,167,8,5,Life Sciences,2,32,3,2,...,3,0,0,0,0,1.0,0.0,0.0,1.0,0.0

#### OverTime encoding (mapping to 1s and 0s)

In [38]:
X_train['OverTime']

417      No
243      No
1628     No
454      No
1532     No
       ...
735      No
1350     No
71       No
320     Yes
552      No
Name: OverTime, Length: 1340, dtype: object

In [39]:
# yes = 1 | no = 0  
X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

In [40]:
display(X_train.head(7))
display(X_test.head(7))

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
417,40,Travel_Rarely,1398,2,4,Life Sciences,3,79,3,5,...,3,20,15,1,12,1.0,0.0,0.0,1.0,0.0
243,40,Travel_Rarely,1300,24,2,Technical Degree,1,62,3,2,...,3,9,8,4,7,0.0,1.0,0.0,0.0,1.0
1628,25,Travel_Rarely,622,13,1,Medical,2,40,3,1,...,3,7,4,0,6,1.0,0.0,0.0,0.0,1.0
454,33,Travel_Rarely,922,1,5,Medical,1,95,4,4,...,3,6,1,0,5,0.0,1.0,0.0,1.0,0.0
1532,39,Travel_Frequently,505,2,4,Technical Degree,3,64,3,3,...,3,19,6,11,8,0.0,1.0,0.0,1.0,0.0
331,27,Non-Travel,210,1,1,Marketing,3,73,3,2,...,3,5,4,1,4,1.0,0.0,0.0,0.0,1.0
1110,32,Non-Travel,1200,1,4,Technical Degree,4,62,3,2,...,2,6,5,1,2,0.0,1.0,0.0,0.0,1.0

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1260,42,Travel_Rarely,855,12,3,Medical,2,57,3,1,...,2,5,3,0,4,0.0,1.0,0.0,0.0,1.0
709,29,Travel_Rarely,906,10,3,Life Sciences,4,92,2,1,...,3,0,0,0,0,0.0,1.0,0.0,1.0,0.0
261,38,Non-Travel,1327,2,2,Life Sciences,4,39,2,2,...,3,8,7,7,5,1.0,0.0,0.0,0.0,1.0
107,25,Travel_Rarely,240,5,3,Marketing,3,46,2,2,...,3,6,4,0,3,1.0,0.0,0.0,0.0,1.0
1639,29,Travel_Rarely,352,6,1,Medical,4,87,2,1,...,3,1,0,0,0,0.0,0.0,1.0,0.0,1.0
228,35,Travel_Frequently,944,1,3,Marketing,3,92,3,3,...,4,10,7,0,8,1.0,0.0,0.0,1.0,0.0
1226,40,Travel_Rarely,369,8,2,Life Sciences,2,92,3,2,...,3,1,0,0,0,0.0,1.0,0.0,1.0,0.0

#### Ordinal encoding for BusinessTravel and MaritalStatus

In [41]:
travel_frequency = ['Non-Travel', 'Travel_Rarely', 'Travel_Frequently'] # 0.0 = Non-Travel, 1.0 = Travel_Rarely, 2.0 = Travel_Frequently
marital_status = ['Single','Married', 'Divorced']

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [43]:
oe_travel = OrdinalEncoder(categories=[travel_frequency])
oe_marital_status = OrdinalEncoder(categories= [marital_status])

In [44]:
X_train['BusinessTravel'] = oe_travel.fit_transform(X_train[['BusinessTravel']])
X_test['BusinessTravel'] = oe_travel.transform(X_test[['BusinessTravel']])

In [45]:
X_train['MaritalStatus'] = oe_marital_status.fit_transform(X_train[['MaritalStatus']])
X_test['MaritalStatus'] = oe_marital_status.transform(X_test[['MaritalStatus']])

In [46]:
display((X_train[['BusinessTravel','MaritalStatus']]).sample(7))
display((X_test[['BusinessTravel','MaritalStatus']]).sample(7))

      BusinessTravel  MaritalStatus
164              0.0            2.0
1108             1.0            1.0
419              0.0            1.0
441              0.0            0.0
1343             1.0            1.0
1119             1.0            0.0
1425             1.0            0.0

      BusinessTravel  MaritalStatus
54               1.0            1.0
683              2.0            0.0
1133             1.0            1.0
564              2.0            0.0
1285             0.0            2.0
1094             1.0            2.0
614              1.0            1.0

In [47]:
max_len = max(len(col) for col in X_train.columns) # finds the length of the largest column name

for col in X_train.columns:
    print(f'{col:<{max_len}} = {X_train[col].nunique()}') # left aligns the column name

Age                      = 43
BusinessTravel           = 3
DailyRate                = 793
DistanceFromHome         = 29
Education                = 5
EducationField           = 6
EnvironmentSatisfaction  = 4
HourlyRate               = 71
JobInvolvement           = 4
JobLevel                 = 5
JobRole                  = 5
JobSatisfaction          = 4
MaritalStatus            = 3
MonthlyIncome            = 1134
MonthlyRate              = 1191
NumCompaniesWorked       = 10
OverTime                 = 2
PercentSalaryHike        = 15
PerformanceRating        = 2
RelationshipSatisfaction = 4
Shift                    = 4
TotalWorkingYears        = 40
TrainingTimesLastYear    = 7
WorkLifeBalance          = 4
YearsAtCompany           = 37
YearsInCurrentRole       = 19
YearsSinceLastPromotion  = 16
YearsWithCurrManager     = 18
Department_Cardiology    = 2
Department_Maternity     = 2
Department_Neurology     = 2
Gender_Female            = 2
Gender_Male              = 2

In [49]:
display((X_train['JobRole'] == 'Other').sum())
display((X_test['JobRole'] == 'Other').sum())

np.int64(434)

np.int64(100)

In [50]:
display((X_train['EducationField'] == 'Other').sum())
display((X_test['EducationField'] == 'Other').sum())

np.int64(75)

np.int64(13)

In [53]:
display((X_train['OverTime'] == 1).sum())
display((X_test['OverTime'] == 1).sum())

np.int64(386)

np.int64(90)

In [55]:
display((y_train == 1).sum())
display((y_test == 1).sum())

np.int64(159)

np.int64(40)

In [57]:
X_train.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1396,38,2.0,1444,1,4,Other,4,88,3,1,...,3,6,2,1,2,0.0,0.0,1.0,0.0,1.0
1135,50,2.0,1234,20,5,Medical,2,41,3,4,...,3,30,8,12,13,0.0,1.0,0.0,0.0,1.0
531,40,2.0,580,5,4,Life Sciences,4,48,2,3,...,3,18,13,1,12,1.0,0.0,0.0,0.0,1.0
795,33,1.0,1017,25,3,Medical,1,55,2,1,...,3,2,2,2,2,0.0,1.0,0.0,0.0,1.0
324,30,1.0,1275,28,2,Medical,4,64,3,2,...,3,10,8,1,9,0.0,1.0,0.0,1.0,0.0
136,51,2.0,1150,8,4,Life Sciences,1,53,1,3,...,3,4,2,0,3,1.0,0.0,0.0,0.0,1.0
1251,49,1.0,1313,11,4,Marketing,4,80,3,2,...,4,5,1,0,4,1.0,0.0,0.0,1.0,0.0

In [58]:
X_test.sample(7)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male
1212,35,2.0,146,2,4,Medical,1,79,2,1,...,4,5,4,1,4,0.0,1.0,0.0,0.0,1.0
1163,48,2.0,365,4,5,Medical,3,89,2,4,...,3,2,2,2,2,0.0,0.0,1.0,0.0,1.0
217,29,1.0,992,1,3,Technical Degree,3,85,3,1,...,2,6,2,1,5,0.0,1.0,0.0,0.0,1.0
858,46,1.0,1402,2,3,Marketing,3,69,3,4,...,3,26,15,15,9,1.0,0.0,0.0,1.0,0.0
1160,37,1.0,1470,10,3,Medical,2,71,3,1,...,1,8,4,7,7,0.0,1.0,0.0,1.0,0.0
1672,46,1.0,1125,10,3,Marketing,3,94,2,3,...,3,3,2,1,2,1.0,0.0,0.0,1.0,0.0
22,34,1.0,419,7,4,Life Sciences,1,53,3,3,...,3,12,6,2,11,0.0,0.0,1.0,1.0,0.0

#### JobRole and EducationField encoding (categorical mapping)

In [59]:
X_train['EducationField'] = X_train['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_train['is_other_JobRole'] = (X_train['JobRole'] == 'Other').astype(int)
X_train['JobRole'] = X_train['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [60]:
(X_train[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
1075               1                 0        3
821                2                 0        1
216                3                 0        1
806                2                 0        2
1093               2                 0        3

In [61]:
X_test['EducationField'] = X_test['EducationField'].map({'Other': 0, 'Life Sciences': 1, 'Medical': 2, 'Marketing': 3, 'Technical Degree': 4, 'Human Resources': 5})
X_test['is_other_JobRole'] = (X_test['JobRole'] == 'Other').astype(int)
X_test['JobRole'] = X_test['JobRole'].map({'Other': 0, 'Nurse': 1,'Therapist': 2, 'Administrative': 3, 'Admin': 4})

In [62]:
(X_test[['EducationField','is_other_JobRole','JobRole']]).sample(5)

      EducationField  is_other_JobRole  JobRole
1161               1                 0        2
1175               2                 1        0
314                2                 1        0
335                2                 0        1
526                4                 0        1

In [66]:
X_train.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [67]:
X_test.dtypes

Age                           int64
BusinessTravel              float64
DailyRate                     int64
DistanceFromHome              int64
Education                     int64
EducationField                int64
EnvironmentSatisfaction       int64
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                       int64
JobSatisfaction               int64
MaritalStatus               float64
MonthlyIncome                 int64
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                      int64
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
Shift                         int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager          int64
Department_Cardiology       float64
Department_Maternity        float64
Department_Neurology        float64
Gender_Female               float64
Gender_Male                 float64
is_other_JobRole              int64
dtype: object

In [78]:
# checking all the dtypes are equal in  train and test sets
display((X_train.dtypes == X_test.dtypes).any() )
display(y_train.dtype == y_test.dtype)

np.True_

True

In [70]:
display(X_train.shape)
display(X_test.shape)

(1340, 34)

(336, 34)

In [75]:
X_train.isna().any().any()

np.False_

In [76]:
X_test.isna().any().any()

np.False_

### Combining Train Cases to train_set and Test Cases to test_set

In [79]:
train_set = pd.concat([X_train, y_train], axis=1)
display(train_set.shape)
train_set.head()

(1340, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
417,40,1.0,1398,2,4,1,3,79,3,5,...,15,1,12,1.0,0.0,0.0,1.0,0.0,0,0
243,40,1.0,1300,24,2,4,1,62,3,2,...,8,4,7,0.0,1.0,0.0,0.0,1.0,1,0
1628,25,1.0,622,13,1,2,2,40,3,1,...,4,0,6,1.0,0.0,0.0,0.0,1.0,1,0
454,33,1.0,922,1,5,2,1,95,4,4,...,1,0,5,0.0,1.0,0.0,1.0,0.0,0,0
1532,39,2.0,505,2,4,4,3,64,3,3,...,6,11,8,0.0,1.0,0.0,1.0,0.0,1,0

In [80]:
test_set = pd.concat([X_test, y_test], axis=1)
display(test_set.shape)
test_set.head()

(336, 35)

,Age,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Cardiology,Department_Maternity,Department_Neurology,Gender_Female,Gender_Male,is_other_JobRole,Attrition
1260,42,1.0,855,12,3,2,2,57,3,1,...,3,0,4,0.0,1.0,0.0,0.0,1.0,0,0
709,29,1.0,906,10,3,1,4,92,2,1,...,0,0,0,0.0,1.0,0.0,1.0,0.0,1,1
261,38,0.0,1327,2,2,1,4,39,2,2,...,7,7,5,1.0,0.0,0.0,0.0,1.0,0,0
107,25,1.0,240,5,3,3,3,46,2,2,...,4,0,3,1.0,0.0,0.0,0.0,1.0,0,1
1639,29,1.0,352,6,1,2,4,87,2,1,...,0,0,0,0.0,0.0,1.0,0.0,1.0,1,0

In [82]:
train_set.to_csv('train_set_datasheet.csv', index=False)
test_set.to_csv('test_set_datasheet.csv', index=False)

## Cross Validation

In [86]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [84]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

### CV with Logistic Regression Model

In [91]:
import warnings
warnings.filterwarnings('ignore')

In [85]:
from sklearn.linear_model import LogisticRegression

In [108]:
lr = LogisticRegression(max_iter=500, random_state=42)

lr_scores = cross_val_score(
    lr,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'LR CV ROC-AUC: {lr_scores}')
print(f'Mean ROC-AUC : {lr_scores.mean()}\n\nRounded ROC-AUC: {round(lr_scores.mean(), 3)} ')

LR CV ROC-AUC: [0.88335375 0.87182203 0.89141949 0.82719809 0.89764301]
Mean ROC-AUC : 0.8742872753897014

Rounded ROC-AUC: 0.874

### CV with Random Forest Classifier

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [107]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)

rf_scores = cross_val_score(
    rf,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'RF CV ROC-AUC: {rf_scores}')
print(f'Mean ROC-AUC : {rf_scores.mean()}\n\nRounded ROC-AUC: {round(rf_scores.mean(), 3)} ')

RF CV ROC-AUC: [0.9475296  0.9357786  0.94286282 0.93299788 0.92750265]
Mean ROC-AUC : 0.9373343106145018

Rounded ROC-AUC: 0.937

### CV with Gradient Boosting Classifier

In [94]:
from sklearn.ensemble import GradientBoostingClassifier

In [105]:
gb = GradientBoostingClassifier(random_state=42)

gb_scores = cross_val_score(
    gb,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

print(f'GB CV ROC-AUC: {gb_scores}')
print(f'Mean ROC-AUC : {gb_scores.mean()}\n\nRounded ROC-AUC: {round(gb_scores.mean(), 3)} ')

GB CV ROC-AUC: [0.9508643  0.94637182 0.96305614 0.95762712 0.92412606]
Mean ROC-AUC : 0.9484090884841733

Rounded ROC-AUC: 0.948

In [111]:
# <model>  : <ROC-AUC value>
LR_Score = round(lr_scores.mean(), 3)
RF_Score = round(rf_scores.mean(), 3)
GB_Score = round(gb_scores.mean(), 3)

In [113]:
Scores = {'Logistic Regression': LR_Score, 'Random Forest Classifier': RF_Score, 'Gradient Boosting Classifier': GB_Score}

best_model = max(Scores, key=Scores.get)
print(f'The Best Model for Training is {best_model}')

The Best Model for Training is Gradient Boosting Classifier